# Generated by Django 3.2.4 on 2021-08-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_data',
            name='drying_time',
            field=models.IntegerField(default=0),
        ),
    ]
