# Generated by Django 3.2.4 on 2021-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_machine_data_drying_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_data',
            name='ship_date',
        ),
        migrations.AddField(
            model_name='machine_data',
            name='date_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='date_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='gus_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='run_time_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='run_time_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='machine_name',
            field=models.CharField(max_length=16),
        ),
    ]
