# Generated by Django 3.2.4 on 2021-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210806_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_data',
            name='gus_usage',
        ),
        migrations.AddField(
            model_name='machine_data',
            name='course_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='date_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='date_ymd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine_data',
            name='gas_usage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='date_d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='date_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='drying_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='machine_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_time_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_time_s',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='unit_no',
            field=models.CharField(max_length=80),
        ),
    ]
