# Generated by Django 3.1.7 on 2021-08-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_gus_usage_machine_data_gas_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_data',
            name='date_y',
            field=models.IntegerField(default=0),
        ),
    ]
