# Generated by Django 3.1.7 on 2021-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_machine_data_date_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_data',
            name='course_no',
            field=models.IntegerField(default=0),
        ),
    ]
