# Generated by Django 3.1.7 on 2021-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_machine_data_course_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_data',
            name='date_machine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='date_d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='date_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='date_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='drying_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='gas_usage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_time_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='run_time_s',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
