# Generated by Django 3.2.4 on 2021-08-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210823_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_data',
            name='unit_no',
            field=models.CharField(max_length=8),
        ),
    ]
