# Generated by Django 3.2.4 on 2021-09-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210822_1226'),
        ('main_app', '0008_alter_machine_data_unit_no'),
    ]

    operations = [
    ]
