# Generated by Django 3.2.4 on 2021-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20210901_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_data',
            name='machine_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='unit_no',
            field=models.CharField(max_length=80),
        ),
    ]
